#!/bin/bash
#requires plymouth-x11 installed
#sudo apt-get install plymouth-x11
echo
echo "Running 10-second test..."
sudo plymouthd ; sudo plymouth --show-splash ; for ((I=0; I<10; I++)); do sleep 1 ; sudo plymouth --update=test$I ; done ; sudo plymouth --quit
exit
