#!/bin/bash
echo ""
echo "    000    --------------------------"
echo "    000  "
echo "    000       ====================        "
echo " 0000 0000    Package Installation          "
echo "   00000                                "
echo "     0     --------------------------"
echo "           "
package=$(</etc/argon/package)
pacaur -S $package
echo ""
echo "               0000                     "
echo "             0000                          "
echo "           0000 "
echo " 0000   0000    ----------------------------------------------------- "
echo "   0000000       process complete, you may now close this window  \\"
echo "     000        -----------------------------------------------------  "

