/* ***** BEGIN LICENSE BLOCK *****
 * Distributed under the BSD license:
 *
 * Copyright (c) 2010, Ajax.org B.V.
 * All rights reserved.
 *
 * Redistribution and use in source and binary forms, with or without
 * modification, are permitted provided that the following conditions are met:
 *     * Redistributions of source code must retain the above copyright
 *       notice, this list of conditions and the following disclaimer.
 *     * Redistributions in binary form must reproduce the above copyright
 *       notice, this list of conditions and the following disclaimer in the
 *       documentation and/or other materials provided with the distribution.
 *     * Neither the name of Ajax.org B.V. nor the
 *       names of its contributors may be used to endorse or promote products
 *       derived from this software without specific prior written permission.
 * 
 * THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS" AND
 * ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED
 * WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE
 * DISCLAIMED. IN NO EVENT SHALL AJAX.ORG B.V. BE LIABLE FOR ANY
 * DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES
 * (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES;
 * LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND
 * ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT
 * (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS
 * SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
 *
 * ***** END LICENSE BLOCK ***** */

define('ace/theme/idle', ['require', 'exports', 'module' , 'ace/lib/dom'], function(require, exports, module) {

exports.isDark = false;
exports.cssClass = "ace-idle";
exports.cssText = "/* THIS THEME WAS AUTOGENERATED BY Theme.tmpl.css (UUID: DDC0CBE1-442B-4CB5-80E4-26E4CFB3A277) */\
.ace-idle .ace_gutter {\
background: #e8e8e8;\
color: #333;\
}\
.ace-idle .ace_print-margin {\
width: 1px;\
background: #e8e8e8;\
}\
.ace-idle {\
background-color: #FFFFFF;\
color: #000000;\
}\
.ace-idle .ace_cursor {\
color: #000000;\
}\
.ace-idle .ace_marker-layer .ace_selection {\
background: #BAD6FD;\
}\
.ace-idle.ace_multiselect .ace_selection.ace_start {\
box-shadow: 0 0 3px 0px #FFFFFF;\
border-radius: 2px;\
}\
.ace-idle .ace_marker-layer .ace_step {\
background: rgb(198, 219, 174);\
}\
.ace-idle .ace_marker-layer .ace_bracket {\
margin: -1px 0 0 -1px;\
border: 1px solid #BFBFBF;\
}\
.ace-idle .ace_marker-layer .ace_active-line {\
background: rgba(0, 0, 0, 0.071);\
}\
.ace-idle .ace_gutter-active-line {\
background-color: rgba(0, 0, 0, 0.071);\
}\
.ace-idle .ace_marker-layer .ace_selected-word {\
border: 1px solid #BAD6FD;\
}\
.ace-idle .ace_fold {\
background-color: #21439C;\
border-color: #000000;\
}\
.ace-idle .ace_keyword{color:#FF5600;}.ace-idle .ace_constant.ace_language{color:#A535AE;}.ace-idle .ace_support.ace_function{color:#A535AE;}.ace-idle .ace_support.ace_constant{color:#A535AE;}.ace-idle .ace_support.ace_class{color:#A535AE;}.ace-idle .ace_support.ace_type{color:#A535AE;}.ace-idle .ace_storage{color:#FF5600;}.ace-idle .ace_invalid{color:#FFFFFF;\
background-color:#990000;}.ace-idle .ace_string{color:#00A33F;}.ace-idle .ace_comment{color:#919191;}.ace-idle .ace_variable{color:#21439C;}.ace-idle .ace_entity.ace_name.ace_function{color:#21439C;}";

var dom = require("../lib/dom");
dom.importCssString(exports.cssText, exports.cssClass);
});
