/* ***** BEGIN LICENSE BLOCK *****
 * Distributed under the BSD license:
 *
 * Copyright (c) 2010, Ajax.org B.V.
 * All rights reserved.
 *
 * Redistribution and use in source and binary forms, with or without
 * modification, are permitted provided that the following conditions are met:
 *     * Redistributions of source code must retain the above copyright
 *       notice, this list of conditions and the following disclaimer.
 *     * Redistributions in binary form must reproduce the above copyright
 *       notice, this list of conditions and the following disclaimer in the
 *       documentation and/or other materials provided with the distribution.
 *     * Neither the name of Ajax.org B.V. nor the
 *       names of its contributors may be used to endorse or promote products
 *       derived from this software without specific prior written permission.
 * 
 * THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS" AND
 * ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED
 * WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE
 * DISCLAIMED. IN NO EVENT SHALL AJAX.ORG B.V. BE LIABLE FOR ANY
 * DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES
 * (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES;
 * LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND
 * ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT
 * (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS
 * SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
 *
 * ***** END LICENSE BLOCK ***** */

define('ace/theme/iceberg', ['require', 'exports', 'module' , 'ace/lib/dom'], function(require, exports, module) {

exports.isDark = true;
exports.cssClass = "ace-iceberg";
exports.cssText = "/* THIS THEME WAS AUTOGENERATED BY Theme.tmpl.css (UUID: b9f1e40f-a2e2-d56e-00b3-5f266364715a) */\
.ace-iceberg .ace_gutter {\
background: #e8e8e8;\
color: #333;\
}\
.ace-iceberg .ace_print-margin {\
width: 1px;\
background: #e8e8e8;\
}\
.ace-iceberg {\
background-color: #323B3D;\
color: #BDD6DB;\
}\
.ace-iceberg .ace_cursor {\
color: #f8f8f0;\
}\
.ace-iceberg .ace_marker-layer .ace_selection {\
background: #2D8DA1;\
}\
.ace-iceberg.ace_multiselect .ace_selection.ace_start {\
box-shadow: 0 0 3px 0px #323B3D;\
border-radius: 2px;\
}\
.ace-iceberg .ace_marker-layer .ace_step {\
background: rgb(198, 219, 174);\
}\
.ace-iceberg .ace_marker-layer .ace_bracket {\
margin: -1px 0 0 -1px;\
border: 1px solid #3b3a32;\
}\
.ace-iceberg .ace_marker-layer .ace_active-line {\
background: #3E4C4F;\
}\
.ace-iceberg .ace_gutter-active-line {\
background-color: #3E4C4F;\
}\
.ace-iceberg .ace_marker-layer .ace_selected-word {\
border: 1px solid #2D8DA1;\
}\
.ace-iceberg .ace_fold {\
background-color: #FFFFFF;\
border-color: #BDD6DB;\
}\
.ace-iceberg .ace_keyword{color:#B1E2F2;}.ace-iceberg .ace_keyword.ace_other.ace_unit{color:#59C0E3;}.ace-iceberg .ace_constant.ace_language{color:#2D8DA1;}.ace-iceberg .ace_constant.ace_numeric{color:#FFFFFF;}.ace-iceberg .ace_constant.ace_character{color:#2D8DA1;}.ace-iceberg .ace_constant.ace_other{color:#2D8DA1;}.ace-iceberg .ace_support.ace_function{color:#ffffff;}.ace-iceberg .ace_support.ace_constant{color:#2D8DA1;}.ace-iceberg .ace_support.ace_constant.ace_property-value{color:#FFFFFF;}.ace-iceberg .ace_support.ace_class{font-style:italic;\
color:#2D8DA1;}.ace-iceberg .ace_support.ace_type{font-style:italic;\
color:#2D8DA1;}.ace-iceberg .ace_storage{color:#2D8DA1;}.ace-iceberg .ace_storage.ace_type{color:#59C0E3;}.ace-iceberg .ace_invalid{color:#f8f8f0;\
background-color:#00a8c6;}.ace-iceberg .ace_invalid.ace_deprecated{color:#f8f8f0;\
background-color:#00a8c6;}.ace-iceberg .ace_string{color:#FFFFFF;}.ace-iceberg .ace_comment{color:#537178;}.ace-iceberg .ace_variable{color:#FFFFFF;}.ace-iceberg .ace_variable.ace_parameter{font-style:italic;}.ace-iceberg .ace_entity.ace_other.ace_attribute-name{color:#2D8DA1;}.ace-iceberg .ace_entity.ace_name.ace_function{color:#FFFFFF;}.ace-iceberg .ace_entity.ace_name.ace_tag{color:#59C0E3;}";

var dom = require("../lib/dom");
dom.importCssString(exports.cssText, exports.cssClass);
});
