/* ***** BEGIN LICENSE BLOCK *****
 * Distributed under the BSD license:
 *
 * Copyright (c) 2010, Ajax.org B.V.
 * All rights reserved.
 *
 * Redistribution and use in source and binary forms, with or without
 * modification, are permitted provided that the following conditions are met:
 *     * Redistributions of source code must retain the above copyright
 *       notice, this list of conditions and the following disclaimer.
 *     * Redistributions in binary form must reproduce the above copyright
 *       notice, this list of conditions and the following disclaimer in the
 *       documentation and/or other materials provided with the distribution.
 *     * Neither the name of Ajax.org B.V. nor the
 *       names of its contributors may be used to endorse or promote products
 *       derived from this software without specific prior written permission.
 * 
 * THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS" AND
 * ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED
 * WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE
 * DISCLAIMED. IN NO EVENT SHALL AJAX.ORG B.V. BE LIABLE FOR ANY
 * DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES
 * (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES;
 * LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND
 * ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT
 * (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS
 * SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
 *
 * ***** END LICENSE BLOCK ***** */

define('ace/theme/otakon', ['require', 'exports', 'module' , 'ace/lib/dom'], function(require, exports, module) {

exports.isDark = true;
exports.cssClass = "ace-otakon";
exports.cssText = "/* THIS THEME WAS AUTOGENERATED BY Theme.tmpl.css (UUID: 190fb297-0ff8-178c-84d3-432c996c6671) */\
.ace-otakon .ace_gutter {\
background: #e8e8e8;\
color: #333;\
}\
.ace-otakon .ace_print-margin {\
width: 1px;\
background: #e8e8e8;\
}\
.ace-otakon {\
background-color: #171417;\
color: #f9f3f9;\
}\
.ace-otakon .ace_cursor {\
color: #f8f8f0;\
}\
.ace-otakon .ace_marker-layer .ace_selection {\
background: #B1A6CA;\
}\
.ace-otakon.ace_multiselect .ace_selection.ace_start {\
box-shadow: 0 0 3px 0px #171417;\
border-radius: 2px;\
}\
.ace-otakon .ace_marker-layer .ace_step {\
background: rgb(198, 219, 174);\
}\
.ace-otakon .ace_marker-layer .ace_bracket {\
margin: -1px 0 0 -1px;\
border: 1px solid #3b3a32;\
}\
.ace-otakon .ace_marker-layer .ace_active-line {\
background: #332d33;\
}\
.ace-otakon .ace_gutter-active-line {\
background-color: #332d33;\
}\
.ace-otakon .ace_marker-layer .ace_selected-word {\
border: 1px solid #B1A6CA;\
}\
.ace-otakon .ace_fold {\
background-color: #E484B2;\
border-color: #f9f3f9;\
}\
.ace-otakon .ace_keyword{color:#CACBDD;}.ace-otakon .ace_keyword.ace_other.ace_unit{color:#B1A6CA;}.ace-otakon .ace_constant.ace_language{color:#F6E6EB;}.ace-otakon .ace_constant.ace_numeric{color:#9eb2d9;}.ace-otakon .ace_constant.ace_character{color:#F6E6EB;}.ace-otakon .ace_constant.ace_other{color:#F6E6EB;}.ace-otakon .ace_support.ace_function{color:#F0B9D4;}.ace-otakon .ace_support.ace_constant{color:#F6E6EB;}.ace-otakon .ace_support.ace_constant.ace_property-value{color:#9eb2d9;}.ace-otakon .ace_support.ace_class{font-style:italic;\
color:#F6E6EB;}.ace-otakon .ace_support.ace_type{font-style:italic;\
color:#F6E6EB;}.ace-otakon .ace_storage{color:#F6E6EB;}.ace-otakon .ace_storage.ace_type{color:#B1A6CA;}.ace-otakon .ace_invalid{color:#f8f8f0;\
background-color:#00a8c6;}.ace-otakon .ace_invalid.ace_deprecated{color:#f8f8f0;\
background-color:#00a8c6;}.ace-otakon .ace_string{color:#9eb2d9;}.ace-otakon .ace_comment{color:#515166;}.ace-otakon .ace_variable{color:#E484B2;}.ace-otakon .ace_variable.ace_parameter{font-style:italic;}.ace-otakon .ace_entity.ace_other.ace_attribute-name{color:#F6E6EB;}.ace-otakon .ace_entity.ace_name.ace_function{color:#E484B2;}.ace-otakon .ace_entity.ace_name.ace_tag{color:#B1A6CA;}";

var dom = require("../lib/dom");
dom.importCssString(exports.cssText, exports.cssClass);
});
