/* ***** BEGIN LICENSE BLOCK *****
 * Distributed under the BSD license:
 *
 * Copyright (c) 2010, Ajax.org B.V.
 * All rights reserved.
 *
 * Redistribution and use in source and binary forms, with or without
 * modification, are permitted provided that the following conditions are met:
 *     * Redistributions of source code must retain the above copyright
 *       notice, this list of conditions and the following disclaimer.
 *     * Redistributions in binary form must reproduce the above copyright
 *       notice, this list of conditions and the following disclaimer in the
 *       documentation and/or other materials provided with the distribution.
 *     * Neither the name of Ajax.org B.V. nor the
 *       names of its contributors may be used to endorse or promote products
 *       derived from this software without specific prior written permission.
 * 
 * THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS" AND
 * ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED
 * WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE
 * DISCLAIMED. IN NO EVENT SHALL AJAX.ORG B.V. BE LIABLE FOR ANY
 * DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES
 * (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES;
 * LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND
 * ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT
 * (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS
 * SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
 *
 * ***** END LICENSE BLOCK ***** */

define('ace/theme/magicwb_(amiga)', ['require', 'exports', 'module' , 'ace/lib/dom'], function(require, exports, module) {

exports.isDark = false;
exports.cssClass = "ace-magicwb-(amiga)";
exports.cssText = "/* THIS THEME WAS AUTOGENERATED BY Theme.tmpl.css (UUID: B0A18BAA-6220-481C-9914-F6D3E51B5410) */\
.ace-magicwb-(amiga) .ace_gutter {\
background: #e8e8e8;\
color: #333;\
}\
.ace-magicwb-(amiga) .ace_print-margin {\
width: 1px;\
background: #e8e8e8;\
}\
.ace-magicwb-(amiga) {\
background-color: #969696;\
color: #000000;\
}\
.ace-magicwb-(amiga) .ace_cursor {\
color: #FFFFFF;\
}\
.ace-magicwb-(amiga) .ace_marker-layer .ace_selection {\
background: #B1B1B1;\
}\
.ace-magicwb-(amiga).ace_multiselect .ace_selection.ace_start {\
box-shadow: 0 0 3px 0px #969696;\
border-radius: 2px;\
}\
.ace-magicwb-(amiga) .ace_marker-layer .ace_step {\
background: rgb(198, 219, 174);\
}\
.ace-magicwb-(amiga) .ace_marker-layer .ace_bracket {\
margin: -1px 0 0 -1px;\
border: 1px solid #FF38FF;\
}\
.ace-magicwb-(amiga) .ace_marker-layer .ace_active-line {\
background: rgba(0, 0, 0, 0.071);\
}\
.ace-magicwb-(amiga) .ace_gutter-active-line {\
background-color: rgba(0, 0, 0, 0.071);\
}\
.ace-magicwb-(amiga) .ace_marker-layer .ace_selected-word {\
border: 1px solid #B1B1B1;\
}\
.ace-magicwb-(amiga) .ace_fold {\
background-color: #FFA995;\
border-color: #000000;\
}\
.ace-magicwb-(amiga) .ace_constant.ace_language{color:#FFA995;}.ace-magicwb-(amiga) .ace_constant.ace_numeric{color:#FFFFFF;}.ace-magicwb-(amiga) .ace_constant.ace_character{color:#FFA995;\
background-color:rgba(0, 0, 255, 0.20);}.ace-magicwb-(amiga) .ace_constant.ace_other{color:#FFA995;\
background-color:rgba(0, 0, 255, 0.20);}.ace-magicwb-(amiga) .ace_support.ace_function{color:#E5B3FF;}.ace-magicwb-(amiga) .ace_support.ace_constant{color:#FFFFFF;}.ace-magicwb-(amiga) .ace_support.ace_class{color:#FFA995;}.ace-magicwb-(amiga) .ace_support.ace_type{color:#FFA995;}.ace-magicwb-(amiga) .ace_storage{color:#3A68A3;}.ace-magicwb-(amiga) .ace_invalid{color:#FFFFFF;\
background-color:#797979;}.ace-magicwb-(amiga) .ace_string{color:#FFFFFF;\
background-color:rgba(255, 0, 0, 0.20);}.ace-magicwb-(amiga) .ace_comment{font-style:italic;\
color:#8D2E75;}.ace-magicwb-(amiga) .ace_variable{color:#FFA995;}.ace-magicwb-(amiga) .ace_variable.ace_language{color:#FFA995;}.ace-magicwb-(amiga) .ace_variable.ace_parameter{font-style:italic;}.ace-magicwb-(amiga) .ace_entity.ace_other.ace_attribute-name{font-style:italic;\
color:#3A68A3;}.ace-magicwb-(amiga) .ace_entity.ace_name.ace_function{color:#FFA995;}.ace-magicwb-(amiga) .ace_entity.ace_name{color:#0000FF;}.ace-magicwb-(amiga) .ace_markup.ace_list{color:#4D4E60;}";

var dom = require("../lib/dom");
dom.importCssString(exports.cssText, exports.cssClass);
});
