/* ***** BEGIN LICENSE BLOCK *****
 * Distributed under the BSD license:
 *
 * Copyright (c) 2010, Ajax.org B.V.
 * All rights reserved.
 *
 * Redistribution and use in source and binary forms, with or without
 * modification, are permitted provided that the following conditions are met:
 *     * Redistributions of source code must retain the above copyright
 *       notice, this list of conditions and the following disclaimer.
 *     * Redistributions in binary form must reproduce the above copyright
 *       notice, this list of conditions and the following disclaimer in the
 *       documentation and/or other materials provided with the distribution.
 *     * Neither the name of Ajax.org B.V. nor the
 *       names of its contributors may be used to endorse or promote products
 *       derived from this software without specific prior written permission.
 * 
 * THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS" AND
 * ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED
 * WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE
 * DISCLAIMED. IN NO EVENT SHALL AJAX.ORG B.V. BE LIABLE FOR ANY
 * DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES
 * (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES;
 * LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND
 * ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT
 * (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS
 * SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
 *
 * ***** END LICENSE BLOCK ***** */

define('ace/theme/amy', ['require', 'exports', 'module' , 'ace/lib/dom'], function(require, exports, module) {

exports.isDark = true;
exports.cssClass = "ace-amy";
exports.cssText = "/* THIS THEME WAS AUTOGENERATED BY Theme.tmpl.css (UUID: 3C01FADD-7592-49DD-B7A5-1B82CA4E57B5) */\
.ace-amy .ace_gutter {\
background: #e8e8e8;\
color: #333;\
}\
.ace-amy .ace_print-margin {\
width: 1px;\
background: #e8e8e8;\
}\
.ace-amy {\
background-color: #200020;\
color: #D0D0FF;\
}\
.ace-amy .ace_cursor {\
color: #7070FF;\
}\
.ace-amy .ace_marker-layer .ace_selection {\
background: rgba(128, 0, 0, 0.50);\
}\
.ace-amy.ace_multiselect .ace_selection.ace_start {\
box-shadow: 0 0 3px 0px #200020;\
border-radius: 2px;\
}\
.ace-amy .ace_marker-layer .ace_step {\
background: rgb(198, 219, 174);\
}\
.ace-amy .ace_marker-layer .ace_bracket {\
margin: -1px 0 0 -1px;\
border: 1px solid #BFBFBF;\
}\
.ace-amy .ace_marker-layer .ace_active-line {\
background: rgba(128, 0, 0, 0.25);\
}\
.ace-amy .ace_gutter-active-line {\
background-color: rgba(128, 0, 0, 0.25);\
}\
.ace-amy .ace_marker-layer .ace_selected-word {\
border: 1px solid rgba(128, 0, 0, 0.50);\
}\
.ace-amy .ace_fold {\
background-color: #50A0A0;\
border-color: #D0D0FF;\
}\
.ace-amy .ace_keyword{color:#A080FF;}.ace-amy .ace_keyword.ace_operator{color:#A0A0FF;}.ace-amy .ace_constant.ace_numeric{color:#7090B0;}.ace-amy .ace_constant.ace_character{color:#666666;}.ace-amy .ace_support.ace_constant{background-color:#200020;}.ace-amy .ace_support.ace_other{color:#A00050;}.ace-amy .ace_storage{color:#B0FFF0;}.ace-amy .ace_invalid.ace_illegal{color:#400080;\
background-color:#FFFF00;}.ace-amy .ace_invalid.ace_deprecated{color:#200020;\
background-color:#CC66FF;}.ace-amy .ace_string{color:#999999;}.ace-amy .ace_variable{color:#50A0A0;}.ace-amy .ace_variable.ace_language{color:#008080;}.ace-amy .ace_variable.ace_parameter{color:#80B0B0;}.ace-amy .ace_entity.ace_name.ace_function{color:#50A0A0;}.ace-amy .ace_entity.ace_name.ace_tag{color:#009090;}";

var dom = require("../lib/dom");
dom.importCssString(exports.cssText, exports.cssClass);
});
