/* ***** BEGIN LICENSE BLOCK *****
 * Distributed under the BSD license:
 *
 * Copyright (c) 2010, Ajax.org B.V.
 * All rights reserved.
 *
 * Redistribution and use in source and binary forms, with or without
 * modification, are permitted provided that the following conditions are met:
 *     * Redistributions of source code must retain the above copyright
 *       notice, this list of conditions and the following disclaimer.
 *     * Redistributions in binary form must reproduce the above copyright
 *       notice, this list of conditions and the following disclaimer in the
 *       documentation and/or other materials provided with the distribution.
 *     * Neither the name of Ajax.org B.V. nor the
 *       names of its contributors may be used to endorse or promote products
 *       derived from this software without specific prior written permission.
 * 
 * THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS" AND
 * ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED
 * WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE
 * DISCLAIMED. IN NO EVENT SHALL AJAX.ORG B.V. BE LIABLE FOR ANY
 * DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES
 * (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES;
 * LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND
 * ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT
 * (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS
 * SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
 *
 * ***** END LICENSE BLOCK ***** */

define('ace/theme/krtheme', ['require', 'exports', 'module' , 'ace/lib/dom'], function(require, exports, module) {

exports.isDark = true;
exports.cssClass = "ace-krtheme";
exports.cssText = "/* THIS THEME WAS AUTOGENERATED BY Theme.tmpl.css (UUID: 87F051F7-B6FB-408C-96F9-467B66C14E9F) */\
.ace-krtheme .ace_gutter {\
background: #e8e8e8;\
color: #333;\
}\
.ace-krtheme .ace_print-margin {\
width: 1px;\
background: #e8e8e8;\
}\
.ace-krtheme {\
background-color: #0B0A09;\
color: #FCFFE0;\
}\
.ace-krtheme .ace_cursor {\
color: #FF9900;\
}\
.ace-krtheme .ace_marker-layer .ace_selection {\
background: rgba(170, 0, 255, 0.45);\
}\
.ace-krtheme.ace_multiselect .ace_selection.ace_start {\
box-shadow: 0 0 3px 0px #0B0A09;\
border-radius: 2px;\
}\
.ace-krtheme .ace_marker-layer .ace_step {\
background: rgb(198, 219, 174);\
}\
.ace-krtheme .ace_marker-layer .ace_bracket {\
margin: -1px 0 0 -1px;\
border: 1px solid rgba(255, 177, 111, 0.32);\
}\
.ace-krtheme .ace_marker-layer .ace_active-line {\
background: #38403D;\
}\
.ace-krtheme .ace_gutter-active-line {\
background-color: #38403D;\
}\
.ace-krtheme .ace_marker-layer .ace_selected-word {\
border: 1px solid rgba(170, 0, 255, 0.45);\
}\
.ace-krtheme .ace_fold {\
background-color: #949C8B;\
border-color: #FCFFE0;\
}\
.ace-krtheme .ace_keyword{color:#949C8B;}.ace-krtheme .ace_constant{color:rgba(210, 117, 24, 0.76);}.ace-krtheme .ace_support{color:#9FC28A;}.ace-krtheme .ace_support.ace_function{color:#85873A;}.ace-krtheme .ace_support.ace_constant{color:#C27E66;}.ace-krtheme .ace_storage{color:#FFEE80;}.ace-krtheme .ace_invalid{color:#F8F8F8;\
background-color:#A41300;}.ace-krtheme .ace_string.ace_regexp{color:rgba(125, 255, 192, 0.65);}.ace-krtheme .ace_comment{font-style:italic;\
color:#706D5B;}.ace-krtheme .ace_variable{color:#D1A796;}.ace-krtheme .ace_variable.ace_language{color:#FF80E1;}.ace-krtheme .ace_meta.ace_tag{color:#BABD9C;}.ace-krtheme .ace_markup.ace_list{background-color:#0F0040;}";

var dom = require("../lib/dom");
dom.importCssString(exports.cssText, exports.cssClass);
});
