var _msg ={
  "$lang": "zh",
  "app.name": "马克飞象<b>专业版</b>",
  "app.title": "马克飞象 - 专为印象笔记打造的Markdown编辑器",
  "app.description": "专为印象笔记打造的Markdown编辑器",
  "Preparing": "加载中",
  "Evernote International": "Evernote International",
  "Link Evernote": "绑定Evernote International账号",
  "Save Evernote": "保存到Evernote International",
  "Link account first": "请先绑定账号",
  "Welcome document": "使用说明",
  "FAQ": "常见问题",
  "About": "关于",
  "Logout": "退出账号",
  "Settings": "设置",
  "Link with Evernote": "绑定 Evernote International 账号",
  "Link with Yinxiang": "绑定印象笔记账号",
  "CURRENT DOCUMENT": "当前文档",
  "Delete document": "删除文档",
  "Donate": "捐赠",
  "Chrome app": "下载Chrome扩展",
  "SYSTEM": "系统",
  "Swtich to basic version": "切换至免费版",
  "Search file": "搜索文件",
  "Open file": "打开文件",
  "Open in new window": "在新窗口中打开",
  "Open in Evernote": "在 Evernote 中打开",
  "Select document": "文档管理",
  "Markdown syntax": "Markdown 语法",
  "Editor theme": "编辑器主题",
  "Toggle resize": "切换全屏",
  "Local draft. Click to sync.": "本地缓存，点击同步",
  "Syncing": "正在同步",
  "Synced": "已同步",
  "Have changes. Click to sync.": "有改动，点击同步",
  "Readonly mode": "只读模式",
  "New document": "新建文档",
  "Profile": "账号",
  "Cancel": "取消",
  "OK": "确定",
  "File Conflict": "文件冲突",
  "FILE_CONFLICT_MSG": "检测到本地有尚未同步的修改，将打开本地版本。请仔细对比本地与Evernote中的内容，以决定同步或删除本地版本。操作前请做好备份。",
  "Hyperlink": "插入链接",
  "Please provide the link URL and an optional title:": "请填写链接URL以及描述（可选）：",
  "Image": "插入图片",
  "Please provide the image URL:": "请填写图片URL：",
  "Import local image...": "插入本地图片...",
  "Delete": "删除文件",
  "Are you sure you want to delete?": "确定删除<code id='remove-filename'></code>？",
  "NOTE:": "注意：",
  "This will not delete the data on Evernote": "如果已同步到Evernote, Evernote中的内容将不会删除",
  "Sync Note Error": "同步文件失败",
  "Error code:": "错误码：",
  "MESSAGE": {
    "UNAUTHORIZED_NOTE": "没有权限打开该笔记，请检查账号状态",
    "ERROR_OPEN_FILE": "打开文件失败",
    "READONLY_MODE": "检测到该文件正在被另一窗口编辑，开启只读模式",
    "Syncing": "正在同步",
    "Downloading image": "下载图片中",
    "Fail to insert image": "插入图片失败",
    "NOT_AUTHED": "尚未绑定账号",
    "Fetching from Evernote": "正在从 Evernote 读取笔记",
    "Successfully link with Evernote": "绑定账号成功！",
    "Server error": "服务器内部错误。请联系hustgock@gmail.com",
    "Loading file": "载入文件中",
    "EXCEED_NOTE_LIMIT": "超过笔记内容限制",
    "EXCEED_ACCOUNT_LIMIT": "账户剩余容量不足",
    "AUTH_ERROR": "Evernote认证错误，请重新绑定账号",
    "AUTH_EXPIRED": "Evernote认证已过期，请重新绑定账号。",
    "RATE_LIMIT": "操作太频繁，请一小时后再操作",
    "ILLEGAL_CONTENT": "内容含有非法字符",
    "UNKNOWN": "未知错误",
    "BAD_DATA_FORMAT": "数据格式有误",
    "PERMISSION_DENIED": "权限不足",
    "INTERNAL_ERROR": "内部错误",
    "DATA_REQUIRED": "缺少必需内容"
  }
}
 var MSG = function(key){ return _msg[key] || key }